DATA:
  ROOT: datasets
  NAME: pokedex
  SUBSET: gen-I
  TEST_PROMPT_FNAME: data/pokemon.txt

  INSTANCE_PROMPT_TEMPLATE: a purcs {} animal
  CLASS_PROMPT_TEMPLATE: a {} animal

  IMAGE_SIZE: 512
  TRAIN_BATCH_SIZE: 2
  NUM_WORKERS: 4
  NUM_IMAGES_PER_CLASS: 3

TRAINER:
  NUM_EPOCHS: 10
  LR: 5.0e-5
  EVAL_FREQ: 5
  MAX_GRAD_NORM: 1.0

  PRIOR_PRESERVATION:
    ENABLE: False
    LOSS_WEIGHT: 1.0

MODEL:
  PRETRAIN_ID: sd2-community/stable-diffusion-2

RANDOM:
  SEED: 42
